name: Formatting

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_fmt:
    name: Check code formatting
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v7
      - name: Install stable toolchain
        run: |
          rustup default stable
          rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
