name: Formatting

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_fmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v5

      - name: Temporarily modify the rust toolchain version
        run: rustup override set 1.87.0

      - name: Check formatting
        run: cargo fmt --all -- --check
