name: Tests

on: [push, pull_request]

jobs:
  run_test_suite:
    name: Run SOM Test Suite
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        interpreter:
          - som-interpreter-ast
          - som-interpreter-bc
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install stable toolchain
        run: rustup default stable
      - name: Compile SOM interpreter
        run: cargo build --release -p ${{ matrix.interpreter }}
      - name: Run test suite
        run: |
          ./target/release/${{ matrix.interpreter }} -c core-lib/Smalltalk core-lib/TestSuite -- TestHarness

  run_own_tests:
    name: Run own tests
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install stable toolchain
        run: rustup default stable
      - name: Run all tests
        run: cargo test
        env:
          RUST_TEST_THREADS: 1
